#!/usr/bin/env perl

use strict;
use warnings;
use YAML::XS 'LoadFile';
use Data::Dumper;
use List::Util 'shuffle';
use Getopt::Long 'GetOptions';

my $config_file = '/etc/postfix/systemhealth.yml';

GetOptions('config=s' => \$config_file) or die "Usage: $0 --config CONFIG\n";

my $config = LoadFile($config_file);

# helpers

sub undertake_check {
    my $check_result = shift;
    my $check_name = shift;

    if ( !$check_result ) {
	print "432 Service temporarily unavailable - $check_name\n";
	exit;
    }
}

sub check_configured {
    my $config = shift;
    my $check = shift;

    return defined ${$config->{checks}}{$check};
}

# user checks

sub check_users_present {
    my $config = shift;

    foreach my $user (shuffle @{$config->{checks}->{user_exists}->{users}}) {
    	print "$user \n";
    	if (not defined getpwnam($user)) {
            return 0;
        }

    }

    return 1;
}

# nfs checks

sub check_nfs_mount {
    my $config = shift;

    foreach my $mount (shuffle @{$config->{checks}->{nfs_mount}->{mounts}}) {
    	print "$mount \n";
	#if (not defined getpwnam($user)) {
	#    return 0;
	#}

    }

    return 1;
}

# sssd checks

sub check_sssd_health {
    return 1;
}

# check configfile for check key
print Dumper($config);
undertake_check(defined $config->{'checks'}, 'systemhealth.yml error');

# what checks are enabled in the config
if (check_configured($config,'nfs_mount')) {
    undertake_check(check_nfs_mount($config), 'nfs_mount');
}

if (check_configured($config,'sssd_health')) {
    undertake_check(check_sssd_health($config), 'sssd_health');
}

if (check_configured($config,'user_exists')) {
    undertake_check(check_users_present($config), 'user_exists');
}

undertake_check(1, 'True test');
undertake_check(0, 'False test');

print "DUNNO\n";
